import {z} from 'zod';
import {context,failure,checkOffice} from '@/lib/server-records';
import {today,paymentTotal,paymentSchema} from '@/lib/records';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s);
const money=z.coerce.number().finite().min(0).max(1e11);
const cancel=z.object({officeId:z.string().min(1),date,moveOut:date,reason:z.string().trim().min(1).max(2000),deductions:money,depositRefund:money,otherRefund:money,finalCharge:money,notes:z.string().max(2000).default(''),vacated:z.boolean(),checks:z.array(z.object({id:z.string(),action:z.enum(['Keep collectible','Returned','Cancelled'])})).max(1000)});
function emptyOffice(o:any){return {...o,status:'Available',leaseClosed:false,company:'',contact:'',email:'',phone:'',trn:'',billingAddress:'',licenseNumber:'',licenseExpiry:'',leaseReference:'',start:'',end:'',rent:0,deposit:0,services:'',notes:''};}
export async function POST(req:Request){try{const {db,owner}=await context(req);const body:any=await req.json();if(body.action==='vacate'){const row:any=await db.prepare('SELECT data,office_id FROM leases WHERE id=? AND owner=?').bind(body.leaseId,owner).first();if(!row)throw new Error('Lease not found.');const lease=JSON.parse(row.data);if(lease.vacated)throw new Error('Vacancy already confirmed.');const r:any=await db.prepare('SELECT data FROM offices WHERE id=? AND owner=?').bind(row.office_id,owner).first();const o=JSON.parse(r.data);if(!o.leaseClosed)throw new Error('This office is no longer awaiting vacancy.');lease.vacated=true;lease.vacatedOn=today();await db.batch([db.prepare('UPDATE offices SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(emptyOffice(o)),row.office_id,owner),db.prepare('UPDATE leases SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(lease),body.leaseId,owner)]);return Response.json({id:body.leaseId});}
const c=cancel.parse(body);if(c.date>today())throw new Error('Cancellation date cannot be in the future.');if(c.moveOut<c.date)throw new Error('Move-out date must be on or after cancellation.');if(c.vacated&&c.moveOut>today())throw new Error('A future move-out cannot be marked vacated.');await checkOffice(db,owner,c.officeId);const r:any=await db.prepare('SELECT data FROM offices WHERE id=? AND owner=?').bind(c.officeId,owner).first();const office=JSON.parse(r.data);if(!office.company||office.leaseClosed)throw new Error('This office has no open tenant lease to cancel.');
const previous=await db.prepare('SELECT data FROM leases WHERE office_id=? AND owner=?').bind(c.officeId,owner).all();const archivedIds=new Set(previous.results.flatMap((r:any)=>JSON.parse(r.data).paymentIds));const rows=await db.prepare('SELECT id,data FROM payments WHERE office_id=? AND owner=?').bind(c.officeId,owner).all();const payments=rows.results.filter((r:any)=>!archivedIds.has(r.id)).map((r:any)=>({...JSON.parse(r.data),id:r.id}));const held=payments.filter((p:any)=>p.direction==='Income'&&p.status==='Cleared').reduce((s:number,p:any)=>s+(p.securityDeposit||0),0);if(c.deductions+c.depositRefund>held+0.001)throw new Error('Deposit deductions and refund exceed deposits actually received.');const pending=payments.filter((p:any)=>p.direction==='Income'&&['Pending','Bounced'].includes(p.status));if(new Set(c.checks.map(x=>x.id)).size!==c.checks.length||c.checks.length!==pending.length||pending.some((p:any)=>!c.checks.some(x=>x.id===p.id)))throw new Error('Review every outstanding income payment.');
const cycle=JSON.stringify([owner,c.officeId,office.company,office.start,office.end,office.leaseReference]);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(cycle));const id='lease-'+Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join(''),batch=[];if(await db.prepare('SELECT id FROM leases WHERE id=? AND owner=?').bind(id,owner).first())throw new Error('This lease was already cancelled.');for(const p of payments){const decision=c.checks.find(x=>x.id===p.id);if(decision&&decision.action!=='Keep collectible'){p.status='Cancelled';p.notes=(p.notes||'')+' [Lease cancellation: '+decision.action+']';}p.leaseId=id;batch.push(db.prepare('UPDATE payments SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(p),p.id,owner));}
const settlementIds:string[]=[];for(const [label,amount,direction] of [['Deposit refund',c.depositRefund,'Expense'],['Other tenant refund',c.otherRefund,'Expense'],['Final cancellation charge',c.finalCharge,'Income']] as const){if(!amount)continue;const pid=crypto.randomUUID();const p=paymentSchema.parse({officeId:c.officeId,leaseId:id,branch:office.branch||'BHB',direction,reference:'SETTLE-'+pid,party:office.company,method:'Transfer',category:'Other',incomeType:'Other income',description:label,amount,due:c.date,status:direction==='Income'?'Pending':'Unpaid',notes:c.reason});settlementIds.push(pid);batch.push(db.prepare('INSERT INTO payments (id,owner,office_id,data) VALUES (?,?,?,?)').bind(pid,owner,c.officeId,JSON.stringify({...p,id:pid})));}
const oldDocs=new Set(previous.results.flatMap((r:any)=>JSON.parse(r.data).documentIds));const docs=await db.prepare('SELECT id FROM documents WHERE office_id=? AND owner=?').bind(c.officeId,owner).all();const lease={...c,id,office,depositReceived:held,paymentIds:[...payments.map((p:any)=>p.id),...settlementIds],settlementIds,documentIds:docs.results.map((d:any)=>d.id).filter((id:string)=>!oldDocs.has(id)),created:new Date().toISOString(),status:'Cancelled'};batch.push(db.prepare('INSERT INTO leases (id,owner,office_id,data) VALUES (?,?,?,?)').bind(id,owner,c.officeId,JSON.stringify(lease)),db.prepare('UPDATE offices SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(c.vacated?emptyOffice(office):{...office,status:'Inactive',leaseClosed:true}),c.officeId,owner));await db.batch(batch);return Response.json({id});}catch(e){return failure(e);}}
