 'use client';
import {useState} from 'react';
import type {Office,Attachment} from '@/lib/records';
function number(phone:string){let n=phone.trim().replace(/[ ()-]/g,'');if(n.startsWith('00'))n='+'+n.slice(2);return /^\+[1-9]\d{7,14}$/.test(n)?n.slice(1):null;}
export default function WhatsAppPanel({offices,documents}:{offices:Office[];documents:Attachment[]}){
 const [mode,setMode]=useState('private'),[officeId,setOfficeId]=useState(''),[message,setMessage]=useState('');
 const tenants=[...offices].sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true})),office=tenants.find(o=>o.id===officeId);
 const recipients=mode==='private'?(office?[office]:[]):tenants.filter(o=>o.status==='Active'&&(o.company||o.contact));
 const unique=recipients.filter((o,i,a)=>!number(o.phone)||a.findIndex(x=>number(x.phone)===number(o.phone))===i);
 return <section className="surface"><div className="surface-head"><h2>WhatsApp messages</h2><a className="secondary" href="https://web.whatsapp.com/" target="_blank" rel="noreferrer">Open WhatsApp Web</a></div><div style={{padding:24}}><p>Sign in to WhatsApp Web using your test business account; opening a chat does not automatically select the sender. Review and send each message in WhatsApp.</p><div className="form-grid"><label className="field"><span>Message type</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="private">Private message</option><option value="announcement">Announcement to active tenants</option></select></label>{mode==='private'&&<label className="field"><span>Tenant / office</span><select aria-label="Tenant / office" value={officeId} onChange={e=>setOfficeId(e.target.value)}><option value="">Choose office</option>{tenants.map(o=><option key={o.id} value={o.id}>{o.code} · {o.company||o.contact||'Client details not added'}</option>)}</select></label>}<label className="field full"><span>Message</span><textarea aria-label="WhatsApp message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Enter your message or announcement…"/></label></div>{mode==='announcement'&&<p>The same announcement is prepared for each active tenant, with duplicate phone numbers removed. Open and send each chat individually. Automatic broadcast is not connected yet.</p>}{!offices.length&&<p>No offices loaded. Add an office in Office portfolio or use Refresh records above.</p>}<div className="doc-list">{unique.map(o=>{const phone=number(o.phone);return <div key={o.id} className="whatsapp-recipient"><div><strong>{o.company||o.contact||'Office '+o.code}</strong><small>Office {o.code} · {o.phone||'No phone recorded'}</small></div>{phone&&message.trim()?<a className="primary" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(message)} target="_blank" rel="noreferrer">Prepare WhatsApp chat</a>:<span>{!phone?'Add phone with country code in Edit office':'Enter a message above'}</span>}</div>})}</div>{mode==='private'&&office&&<><h3>Tenant documents</h3><p>Download the document, then attach it in the WhatsApp chat. Private dashboard links cannot be opened by tenants.</p><div className="doc-list">{documents.filter(d=>d.officeId===office.id).map(d=><a key={d.id} href={'/api/documents?id='+encodeURIComponent(d.id)} target="_blank" rel="noreferrer"><strong>{d.name}</strong><span>{d.category} · Open / download</span></a>)}</div></>}</div></section>;
}
