import type {Database} from '@/db';
// Owner's notification address: Gmail notifications are sent from and to this account.
export const NOTIFY_EMAIL=(process.env.NOTIFY_EMAIL||'owner@example.com').toLowerCase();
export const GMAIL_ACCOUNT=NOTIFY_EMAIL;
export function gmailConfig(){const e=process.env;return {clientId:e.GMAIL_CLIENT_ID||'',clientSecret:e.GMAIL_CLIENT_SECRET||'',key:e.GMAIL_ENCRYPTION_KEY||'',redirect:e.GMAIL_REDIRECT_URI||''};}
export function gmailReady(){const c=gmailConfig();return !!(c.clientId&&c.clientSecret&&c.key&&c.redirect);}
function bytes(s:string){return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
export function base64url(bytes:Uint8Array){return btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function key(){const raw=bytes(gmailConfig().key);if(raw.length!==32)throw new Error('Gmail encryption key must be 32 bytes.');return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
export async function seal(data:any){const iv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(JSON.stringify(data)));return JSON.stringify({iv:btoa(String.fromCharCode(...iv)),value:btoa(String.fromCharCode(...new Uint8Array(encrypted)))});}
export async function unseal(data:string){const p=JSON.parse(data),out=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(p.iv)},await key(),bytes(p.value));return JSON.parse(new TextDecoder().decode(out));}
export async function hash(value:string){return base64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))));}
export async function googleToken(fields:Record<string,string>){const c=gmailConfig(),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,...fields})});if(!r.ok)throw new Error('Google authorization failed. Reconnect Gmail.');return await r.json() as any;}
export async function sendGmail(db:Database,owner:string,subject:string,text:string,replyTo?:string){const row:any=await db.prepare('SELECT data FROM email_connections WHERE id=? AND owner=?').bind('gmail:'+owner,owner).first();if(!row)return false;const token=await unseal(row.data);if(token.expires<Date.now()+60000){const next=await googleToken({grant_type:'refresh_token',refresh_token:token.refresh});token.access=next.access_token;token.expires=Date.now()+next.expires_in*1000;await db.prepare('UPDATE email_connections SET data=? WHERE id=? AND owner=?').bind(await seal(token),'gmail:'+owner,owner).run();}
const clean=(s:string)=>s.replace(/[\r\n]/g,'');const mime=['From: '+GMAIL_ACCOUNT,'To: '+GMAIL_ACCOUNT,...(replyTo?['Reply-To: '+clean(replyTo)]:[]),'Subject: =?UTF-8?B?'+btoa(String.fromCharCode(...new TextEncoder().encode(clean(subject))))+'?=','MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',''+btoa(String.fromCharCode(...new TextEncoder().encode(text)))].join('\r\n');const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:'Bearer '+token.access,'Content-Type':'application/json'},body:JSON.stringify({raw:base64url(new TextEncoder().encode(mime))})});if(!response.ok)throw new Error('Gmail could not send this notification. Check the connection.');return true;}
