import {z} from 'zod';
const date=z.string().refine(x=>x===''||(/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x),'Use a valid date');
const str=z.string().max(2000).default('');
const cash=z.coerce.number().finite().min(0).max(1e11);
export const officeSchema=z.object({id:z.string().optional(),code:z.string().trim().min(1).max(80),branch:z.enum(['BHB','111']).default('BHB'),kind:z.enum(['Physical','Virtual']),status:z.enum(['Available','Active','Reserved','Inactive']),location:str,area:z.coerce.number().finite().min(0).max(1e7).optional(),desks:z.coerce.number().int().min(0).max(100000).optional(),company:str,contact:str,email:z.union([z.literal(''),z.string().email()]).default(''),phone:str,licenseNumber:str,licenseExpiry:date.default(''),leaseReference:str,start:date.default(''),end:date.default(''),rent:cash,period:z.enum(['Yearly','Monthly']),deposit:cash,vat:z.coerce.number().finite().min(0).max(100),services:str,notes:str}).superRefine((o,c)=>{if(o.start&&o.end&&o.end<o.start)c.addIssue({code:'custom',path:['end'],message:'Lease end must be after start'});if(o.status==='Active'&&(!o.company||!o.start||!o.end))c.addIssue({code:'custom',message:'Active offices need a company and lease dates'});});
export const paymentSchema=z.object({id:z.string().optional(),officeId:z.string().nullable().default(null),direction:z.enum(['Income','Expense']),branch:z.enum(['BHB','111']).default('BHB'),reference:z.string().trim().min(1).max(120),party:z.string().trim().min(1).max(200),incomeType:z.enum(['Rent','PRO service','Other income']).default('Rent'),bankName:z.string().trim().max(200).default(''),method:z.enum(['Check','Transfer','Cash']),category:z.enum(['Payroll','Rent','Utilities','Supplies','Other']).default('Rent'),description:str,entryDate:date.default(''),due:date,amount:cash,vatAmount:cash.default(0),securityDeposit:cash.default(0),status:z.enum(['Pending','Cleared','Bounced','Cancelled','Unpaid','Paid']),actual:date.default(''),notes:str}).superRefine((p,c)=>{if(paymentTotal(p)<=0)c.addIssue({code:'custom',path:['amount'],message:'Enter a positive payment amount'});if(p.direction==='Expense'&&(p.vatAmount||p.securityDeposit))c.addIssue({code:'custom',message:'Income VAT and deposits cannot be added to an expense'});if(!p.due)c.addIssue({code:'custom',path:['due'],message:'Enter a due date'});if(['Cleared','Paid'].includes(p.status)&&!p.actual)c.addIssue({code:'custom',path:['actual'],message:'Enter actual cash date'});if(p.direction==='Income'&&!['Pending','Cleared','Bounced','Cancelled'].includes(p.status)||p.direction==='Expense'&&!['Unpaid','Paid','Cancelled'].includes(p.status))c.addIssue({code:'custom',path:['status'],message:'Invalid payment status'});});
export type Office=z.infer<typeof officeSchema>&{id:string};
export type Payment=z.infer<typeof paymentSchema>&{id:string};
export type Attachment={id:string;officeId:string;paymentId:string|null;name:string;category:string;mime:string;size:number;created:string};
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function paymentTotal(p:Pick<Payment,'direction'|'amount'>&Partial<Pick<Payment,'vatAmount'|'securityDeposit'>>){return p.amount+(p.direction==='Income'?(p.vatAmount||0)+(p.securityDeposit||0):0);}
export function cashMetrics(payments:Payment[],month:string,asof:string){const next=new Date(asof+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+30);const end=next.toISOString().slice(0,10);const sum=(fn:(p:Payment)=>boolean)=>payments.filter(fn).reduce((a,p)=>a+paymentTotal(p),0);const cleared=(p:Payment)=>p.direction==='Income'&&p.status==='Cleared';const paid=(p:Payment)=>p.direction==='Expense'&&p.status==='Paid';const pending=(p:Payment)=>p.direction==='Income'&&p.status==='Pending';const unpaid=(p:Payment)=>p.direction==='Expense'&&p.status==='Unpaid';const inMonth=(d:string)=>d.slice(0,7)===month;const cashIn=sum(p=>cleared(p)&&inMonth(p.actual)),cashOut=sum(p=>paid(p)&&inMonth(p.actual));const received=payments.filter(p=>cleared(p)&&inMonth(p.actual));const rentIncome=received.filter(p=>(p.incomeType||'Rent')==='Rent').reduce((a,p)=>a+p.amount,0),proIncome=received.filter(p=>p.incomeType==='PRO service').reduce((a,p)=>a+p.amount,0),otherIncome=received.filter(p=>p.incomeType==='Other income').reduce((a,p)=>a+p.amount,0),vatCollected=received.reduce((a,p)=>a+(p.vatAmount||0),0),depositsReceived=received.reduce((a,p)=>a+(p.securityDeposit||0),0);return{rentIncome,proIncome,otherIncome,vatCollected,depositsReceived,cashIn,cashOut,net:cashIn-cashOut,pending:sum(pending),unpaid:sum(unpaid),checks:payments.filter(p=>pending(p)&&p.method==='Check').length,overdue:payments.filter(p=>pending(p)&&p.method==='Check'&&p.due<asof).length,expensesOverdue:payments.filter(p=>unpaid(p)&&p.due<asof).length,nextIn:sum(p=>pending(p)&&p.due>=asof&&p.due<end),nextOut:sum(p=>unpaid(p)&&p.due>=asof&&p.due<end),planned:cashIn-cashOut+sum(p=>pending(p)&&inMonth(p.due))-sum(p=>unpaid(p)&&inMonth(p.due))};}

export function branchRecords<T extends {offices:Office[];payments:Payment[];documents:Attachment[]}>(records:T,branch:string){const offices=records.offices.filter(o=>(o.branch||'BHB')===branch),ids=new Set(offices.map(o=>o.id));return {offices,payments:records.payments.filter(p=>p.officeId?ids.has(p.officeId):(p.branch||'BHB')===branch),documents:records.documents.filter(d=>ids.has(d.officeId))};}
