import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
import {paymentTotal,type Office,type Payment} from './records';
const NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const parse=(s:Uint8Array)=>new DOMParser().parseFromString(strFromU8(s),'application/xml');
const serialize=(d:Document)=>strToU8(new XMLSerializer().serializeToString(d));
const serial=(s:string)=>Math.round((Date.parse(s+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000);
function dateValue(v:string){if(!v)return '';if(/^\d+(\.\d+)?$/.test(v))return new Date(Date.UTC(1899,11,30)+Number(v)*86400000).toISOString().slice(0,10);if(/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10);throw new Error('Dates must be Excel dates or YYYY-MM-DD.');}
function getSheets(files:Record<string,Uint8Array>){if(!files['xl/workbook.xml'])throw new Error('Choose an .xlsx workbook.');const book=parse(files['xl/workbook.xml']),rels=parse(files['xl/_rels/workbook.xml.rels']);return [...book.getElementsByTagNameNS(NS,'sheet')].map(s=>{const id=s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const target=[...rels.getElementsByTagName('Relationship')].find(r=>r.getAttribute('Id')===id)?.getAttribute('Target')||'';return{name:s.getAttribute('name'),path:target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'')};});}
export async function readWorkbook(file:File,offices:Office[]){if(file.size>15*1024*1024)throw new Error('Workbook limit is 15 MB.');const files=unzipSync(new Uint8Array(await file.arrayBuffer())),sheets=getSheets(files);const ss=files['xl/sharedStrings.xml']?[...parse(files['xl/sharedStrings.xml']).getElementsByTagNameNS(NS,'si')].map(e=>e.textContent||''):[];const records:Partial<Payment>[]=[],errors:string[]=[];
for(const name of ['Incoming Checks','Expenses']){const sheet=sheets.find(s=>s.name===name);if(!sheet)throw new Error('Use the cash-flow workbook with Incoming Checks and Expenses sheets.');const xml=parse(files[sheet.path]);for(const row of [...xml.getElementsByTagNameNS(NS,'row')]){const rn=Number(row.getAttribute('r'));if(rn<6)continue;const c:Record<string,string>={};for(const cell of [...row.getElementsByTagNameNS(NS,'c')]){const addr=(cell.getAttribute('r')||'').replace(/\d/g,'');const value=cell.getElementsByTagNameNS(NS,'v')[0]?.textContent||'';c[addr]=cell.getAttribute('t')==='s'?ss[Number(value)]||'':cell.getAttribute('t')==='inlineStr'?cell.getElementsByTagNameNS(NS,'is')[0]?.textContent||'':value;}
const income=name==='Incoming Checks';if(!['A','B','C','D','E','F',...(income?['G','H','I','J']:[])].some(k=>c[k]))continue;
try{const notes=c[income?'J':'I']||'',code=notes.match(/\[Office: ([^\]]+)\]/)?.[1];const branch=notes.match(/\[Branch: (BHB|111)\]/)?.[1];const matches=offices.filter(o=>o.code===code&&(!branch||(o.branch||'BHB')===branch));if(code&&matches.length>1)throw new Error('Office number is used in two branches. Add [Branch: BHB] or [Branch: 111] in Notes.');const office=code?matches[0]:null;if(code&&!office)throw new Error('Office '+code+' does not exist. Add it before importing.');const p={incomeType:notes.match(/\[Income: (Rent|PRO service|Other income)\]/)?.[1]||'Rent',description:income?(notes.match(/\[Service: ([^\]]*)\]/)?.[1]||''):(c.D||''),branch:office?.branch||branch||'BHB',direction:income?'Income':'Expense',reference:(income?c.C:c.A)||c.A||'',party:c.B||'',method:income?c.D||'Check':notes.match(/\[Method: (Check|Cash|Transfer)\]/)?.[1]||'Transfer',category:income?'Rent':c.C||'Other',entryDate:income?dateValue(c.E||''):'',due:dateValue(c[income?'F':'E']||''),amount:Number(c[income?'G':'F'])-(income?Number(notes.match(/\[VAT: ([0-9.]+)\]/)?.[1]||0)+Number(notes.match(/\[Deposit: ([0-9.]+)\]/)?.[1]||0):0),vatAmount:income?Number(notes.match(/\[VAT: ([0-9.]+)\]/)?.[1]||0):0,securityDeposit:income?Number(notes.match(/\[Deposit: ([0-9.]+)\]/)?.[1]||0):0,status:c[income?'H':'G']||'',actual:dateValue(c[income?'I':'H']||''),notes:notes.replace(/\s*\[Office: [^\]]+\]/g,'').replace(/\s*\[Method: (Check|Cash|Transfer)\]/g,'').replace(/\s*\[(VAT|Deposit): [0-9.]+\]/g,'').replace(/\s*\[Branch: (BHB|111)\]/g,'').replace(/\s*\[Income: (Rent|PRO service|Other income)\]/g,'').replace(/\s*\[Service: [^\]]*\]/g,''),officeId:office?.id||null};if(!p.reference||!p.party||!p.due||!p.status||!Number.isFinite(p.amount)||p.amount<0||paymentTotal(p as Payment)<=0)throw new Error('Reference, payer, due date, positive amount and status are required.');if(['Paid','Cleared'].includes(p.status)&&!p.actual)throw new Error('Enter an actual cash date for a completed payment.');if(!['Check','Transfer','Cash'].includes(p.method))throw new Error('Use Check, Transfer or Cash.');if(!(income?['Pending','Cleared','Bounced','Cancelled']:['Unpaid','Paid','Cancelled']).includes(p.status))throw new Error('Invalid status.');if(!['Payroll','Rent','Utilities','Supplies','Other'].includes(p.category))throw new Error('Use Payroll, Rent, Utilities, Supplies or Other.');records.push(p as Partial<Payment>);}catch(e){errors.push(name+' row '+rn+': '+(e as Error).message);}}
}return{records,errors};}
export async function exportWorkbook(payments:Payment[],offices:Office[],month:string,asof:string){const files=unzipSync(new Uint8Array(await(await fetch('/cash-flow-template.xlsx')).arrayBuffer()));const sheets=getSheets(files);for(const name of ['Incoming Checks','Expenses']){const inc=name==='Incoming Checks',entries=payments.filter(p=>p.direction===(inc?'Income':'Expense'));if(entries.length>500)throw new Error('The workbook supports 500 income entries and 500 expenses.');const sheet=sheets.find(s=>s.name===name)!;const xml=parse(files[sheet.path]),data=xml.getElementsByTagNameNS(NS,'sheetData')[0];const cols=inc?'ABCDEFGHIJ':'ABCDEFGHI';for(const row of [...data.getElementsByTagNameNS(NS,'row')]){if(Number(row.getAttribute('r'))>=6)for(const cell of [...row.getElementsByTagNameNS(NS,'c')])if(cols.includes((cell.getAttribute('r')||'').replace(/\d/g,''))){while(cell.firstChild)cell.removeChild(cell.firstChild);cell.removeAttribute('t');}}
entries.forEach((p,i)=>{const rn=i+6;let row=[...data.getElementsByTagNameNS(NS,'row')].find(r=>r.getAttribute('r')===String(rn));if(!row){row=xml.createElementNS(NS,'row');row.setAttribute('r',String(rn));data.appendChild(row);}const office=offices.find(o=>o.id===p.officeId);const notes=p.notes+(inc?' [Income: '+(p.incomeType||'Rent')+'] [Service: '+(p.description||'').replace(/\]/g,')')+']':'')+' [Branch: '+(office?.branch||p.branch||'BHB')+']'+(inc?' [VAT: '+(p.vatAmount||0)+'] [Deposit: '+(p.securityDeposit||0)+']':'')+(office?' [Office: '+office.code+']':'')+(!inc?' [Method: '+p.method+']':'');const vals=inc?[p.id,p.party,p.reference,p.method,p.entryDate?serial(p.entryDate):null,serial(p.due),paymentTotal(p),p.status,p.actual?serial(p.actual):null,notes]:[p.reference,p.party,p.category,p.description,serial(p.due),paymentTotal(p),p.status,p.actual?serial(p.actual):null,notes];vals.forEach((v,j)=>{const addr=cols[j]+rn;let cell=[...row!.getElementsByTagNameNS(NS,'c')].find(c=>c.getAttribute('r')===addr);if(!cell){cell=xml.createElementNS(NS,'c');cell.setAttribute('r',addr);row!.appendChild(cell);}if(v===null)return;if(typeof v==='number'){const el=xml.createElementNS(NS,'v');el.textContent=String(v);cell.appendChild(el);}else{cell.setAttribute('t','inlineStr');const is=xml.createElementNS(NS,'is'),t=xml.createElementNS(NS,'t');t.textContent=String(v);is.appendChild(t);cell.appendChild(is);}});});files[sheet.path]=serialize(xml);}
const control=sheets.find(s=>s.name==='Data & Targets')!;const xml=parse(files[control.path]);for(const [a,v] of [['C9',serial(month+'-01')],['C10',serial(asof)]] as [string,number][]){const c=[...xml.getElementsByTagNameNS(NS,'c')].find(c=>c.getAttribute('r')===a)!;while(c.firstChild)c.removeChild(c.firstChild);c.removeAttribute('t');const el=xml.createElementNS(NS,'v');el.textContent=String(v);c.appendChild(el);}files[control.path]=serialize(xml);const book=parse(files['xl/workbook.xml']);let calc=book.getElementsByTagNameNS(NS,'calcPr')[0];if(!calc){calc=book.createElementNS(NS,'calcPr');book.documentElement.appendChild(calc);}calc.setAttribute('fullCalcOnLoad','1');calc.setAttribute('forceFullCalc','1');calc.setAttribute('calcMode','auto');files['xl/workbook.xml']=serialize(book);return new Blob([zipSync(files,{level:6}) as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
