import {buildWorkbook} from './period-report';
import {paymentTotal,today,type Office,type Payment,type Attachment} from './records';
export function exportOfficeReport(offices:Office[],payments:Payment[],documents:Attachment[],scope:string){
 const ids=new Set(offices.map(o=>o.id)),ps=payments.filter(p=>p.officeId&&ids.has(p.officeId)),docs=documents.filter(d=>ids.has(d.officeId));
 const code=(id:string|null)=>offices.find(o=>o.id===id)?.code||'';
 const columns=['Office number','Branch','Type','Status','Location / registered address','Area (sq. ft.)','Desks','Company / tenant','Contact person','Email','Phone','Tenant TRN','Billing address','Trade licence number','Licence expiry','Lease reference','Lease start','Lease end','Rent (AED, excl. VAT)','Rent period','VAT (%)','Agreed security deposit (AED)','Services','Notes','Collected rent / services (AED)','VAT collected (AED)','Deposits received (AED)','Pending income incl. VAT / deposits (AED)','Document count'];
 const rows=offices.map(o=>{const p=ps.filter(p=>p.officeId===o.id),received=p.filter(p=>p.direction==='Income'&&p.status==='Cleared');return [o.code,o.branch||'BHB',o.kind,o.status,o.location,o.area??'',o.desks??'',o.company,o.contact,o.email,o.phone,o.trn||'',o.billingAddress||'',o.licenseNumber,o.licenseExpiry,o.leaseReference,o.start,o.end,o.rent,o.period,o.vat,o.deposit,o.services,o.notes,received.reduce((s,p)=>s+p.amount,0),received.reduce((s,p)=>s+(p.vatAmount||0),0),received.reduce((s,p)=>s+(p.securityDeposit||0),0),p.filter(p=>p.direction==='Income'&&p.status==='Pending').reduce((s,p)=>s+paymentTotal(p),0),docs.filter(d=>d.officeId===o.id).length];});
 return buildWorkbook([{name:'Report information',rows:[['BHB BUSINESS CENTRE — OFFICE REPORT'],['Office list',scope],['Exported on',today()],['Offices',offices.length],['Currency','AED'],['Scope','Current office list, including search and status filters.'],['Payment totals','Current records, all dates.'],['Documents','Attachment inventory only; files are not embedded.'],['Security deposits','Agreed and received amounts, not a refund-adjusted balance.']]},{name:'Office details',rows:[columns,...rows]},{name:'Payments',rows:[['Office','Reference','Bank','Client / supplier','Direction','Income category','Method','Due date','Actual cash date','Base amount (AED)','VAT (AED)','Security deposit (AED)','Total payment (AED)','Status','Category','Description','Notes'],...ps.map(p=>[code(p.officeId),p.reference,p.bankName||'',p.party,p.direction,p.direction==='Income'?(p.incomeType||'Rent'):'',p.method,p.due,p.actual,p.amount,p.vatAmount||0,p.securityDeposit||0,paymentTotal(p),p.status,p.category,p.description,p.notes])]},{name:'Document inventory',rows:[['Office','Document name','Type','Related payment','Uploaded on','Size (bytes)'],...docs.map(d=>[code(d.officeId),d.name,d.category,ps.find(p=>p.id===d.paymentId)?.reference||'',d.created,d.size])]}]);
}
