import {zipSync,strToU8} from 'fflate';
import {paymentTotal,type Office,type Payment} from './records';
export function periodFigures(payments:Payment[],start:string,end:string){
 if(!start||!end||start>end)throw new Error('Choose a valid start and end date.');
 const within=(d:string)=>!!d&&d>=start&&d<=end;
 const cash=payments.filter(p=>['Cleared','Paid'].includes(p.status)&&within(p.actual));
 const scheduled=payments.filter(p=>within(p.due));
 const sum=(a:Payment[],direction:string)=>a.filter(p=>p.direction===direction).reduce((s,p)=>s+paymentTotal(p),0);
 const incoming=sum(cash,'Income'),outgoing=sum(cash,'Expense');
 const income=cash.filter(p=>p.direction==='Income');const rentIncome=income.filter(p=>(p.incomeType||'Rent')==='Rent').reduce((s,p)=>s+p.amount,0),proIncome=income.filter(p=>p.incomeType==='PRO service').reduce((s,p)=>s+p.amount,0),otherIncome=income.filter(p=>p.incomeType==='Other income').reduce((s,p)=>s+p.amount,0),vatCollected=income.reduce((s,p)=>s+(p.vatAmount||0),0),depositsReceived=income.reduce((s,p)=>s+(p.securityDeposit||0),0);return {rentIncome,proIncome,otherIncome,vatCollected,depositsReceived,cash,scheduled,incoming,outgoing,net:incoming-outgoing,pending:sum(scheduled.filter(p=>p.status==='Pending'),'Income'),unpaid:sum(scheduled.filter(p=>p.status==='Unpaid'),'Expense')};
}
export function exportPeriodReport(payments:Payment[],offices:Office[],start:string,end:string){
 const f=periodFigures(payments,start,end),office=(id:string|null)=>offices.find(o=>o.id===id)?.code||'Unassigned';
 const columns=['Office','Client / supplier','Bank','Reference','Type','Income category','Method','Due date','Actual cash date','Rent / base amount (AED)','VAT (AED)','Security deposit (AED)','Total payment (AED)','Current status','Description'];
 const rows=(a:Payment[])=>[columns,...a.map(p=>[office(p.officeId),p.party,p.bankName||'',p.reference,p.direction,p.direction==='Income'?(p.incomeType||'Rent'):'',p.method,p.due,p.actual,p.amount,p.vatAmount||0,p.securityDeposit||0,paymentTotal(p),p.status,p.description])];
 const sheets=[{name:'Period summary',rows:[['BHB BUSINESS CENTRE — PERIOD REPORT'],['Start date',start],['End date',end],['Currency','AED'],[],['Actual income received',f.incoming],['Actual expenses paid',f.outgoing],['Net cash movement',f.net],['Rent income received',f.rentIncome],['PRO service income received',f.proIncome],['Other income received',f.otherIncome],['VAT collected',f.vatCollected],['Security deposits received',f.depositsReceived],['Pending income due in period',f.pending],['Unpaid expenses due in period',f.unpaid],[],['Cash movements use actual cash dates. Scheduled payments use due dates.'],['Both start and end dates are included. Statuses reflect current records.'],['This report is not a historical closing balance or a workbook import file.']]},{name:'Cash movements',rows:rows(f.cash)},{name:'Scheduled payments',rows:rows(f.scheduled)}];
 return buildWorkbook(sheets);
}
export function buildWorkbook(sheets:{name:string;rows:(string|number)[][]}[]){
 const escape=(v:unknown)=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));
 const col=(i:number)=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',files:Record<string,Uint8Array>={};
 const put=(path:string,xml:string)=>files[path]=strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+xml);
 put('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+sheets.map((_,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>');
 put('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 put('xl/workbook.xml','<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>'<sheet name="'+s.name+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>');
 put('xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'<Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
 put('xl/styles.xml','<styleSheet xmlns="'+ns+'"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF202020"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf fontId="0" fillId="0" borderId="0" xfId="0"/><xf fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf fontId="0" fillId="0" borderId="0" xfId="0" numFmtId="4" applyNumberFormat="1"/></cellXfs></styleSheet>');
 sheets.forEach((s,i)=>put('xl/worksheets/sheet'+(i+1)+'.xml','<worksheet xmlns="'+ns+'"><sheetViews><sheetView workbookViewId="0">'+(i?'<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>':'')+'</sheetView></sheetViews><cols><col min="1" max="1" width="'+(i?'18':'75')+'" customWidth="1"/><col min="2" max="14" width="24" customWidth="1"/></cols><sheetData>'+s.rows.map((row,r)=>'<row r="'+(r+1)+'">'+row.map((v,c)=>'<c r="'+col(c)+(r+1)+'" s="'+(r===0?'1':typeof v==='number'?'2':'0')+'"'+(typeof v==='number'?'><v>'+v+'</v>':' t="inlineStr"><is><t xml:space="preserve">'+escape(v)+'</t></is>')+'</c>').join('')+'</row>').join('')+'</sheetData>'+(i?'<autoFilter ref="A1:'+col(Math.max(1,...s.rows.map(r=>r.length))-1)+s.rows.length+'"/>':'')+'</worksheet>'));
 return new Blob([zipSync(files,{level:6}) as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
